"""empty message

Revision ID: 1a10614da7ef
Revises: 012ba3b33f55
Create Date: 2024-05-21 17:47:06.994760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a10614da7ef'
down_revision = '012ba3b33f55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('style', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'style')
    # ### end Alembic commands ###
